vss_portal_web/Controllers/AllPostsController.cs
using DBConect;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace vss_portal_web.Controllers
{
    public class AllPostsController : Controller
    {
        // GET: AllPosts
        public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            ViewData["fullNameUser"] = CheckLoginRole.getUserName();
            ViewData["checkRoleLogin"] = CheckLoginRole.check();
            var list = new ActionPost().GetListPostsAllPostHome(searchString, page, pageSize);

            return View(list);
        }
    }
}

vss_portal_web/Controllers/LoginForGuestController.cs
using DBConect;
using DBConect.conmon;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Security;
using vss_portal_web.Areas.Admin.Code;
using vss_portal_web.Areas.Admin.Models;
using vss_portal_web.Models;

namespace vss_portal_web.Controllers
{
    public class LoginForGuestController : Controller
    {
        // GET: LoginForGuest
        public ActionResult Index()
        {
            var cookieName = SessionHelper.GetSession();
            var action = new ActionPost();
            var listPost = action.GetListPost();
            if (cookieName != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(listPost);
        }

        [HttpPost]
        public ActionResult Index(LoginModel model)
        {
            var action = new ActionPost();
            var listPost = action.GetListPost();

            RedirectModel dataRedirect = TempData["myDataRedirect"] as RedirectModel;
            if (new LdapAuthentication().AuthenticateUserV2(model.UserName, model.PassWord) && ModelState.IsValid)
            {
                if (dataRedirect != null)
                {
                    return RedirectToAction(dataRedirect.IndexRedirect, dataRedirect.ControllerRedirect);
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.checkPermision = "";
                ViewBag.showModel = true;
                ModelState.AddModelError("", "Tên đăng nhập hoặc mật khẩu không đúng");
            }
            return View(listPost);
        }
    }
}

vss_portal_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Trang tin nội bộ VSS</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">
    <link rel="stylesheet"
          href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <!-- Favicons -->
    <link href="~/assets/img/vt.png" rel="icon">
    @*<link href="~/assets/img/favicon.png" rel="icon">
        <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">*@

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">

    <link href="~/assets/Tokenfield/dist/css/bootstrap-tokenfield.css" rel="stylesheet" />
    <link href="~/assets/Tokenfield/dist/css/bootstrap-tokenfield.min.css" rel="stylesheet" />
    <link href="~/assets/Tokenfield/dist/css/tokenfield-typeahead.css" rel="stylesheet" />
    <link href="~/assets/Tokenfield/dist/css/tokenfield-typeahead.min.css" rel="stylesheet" />
    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>

<body>

    <!-- ======= Top Bar ======= -->
    @*<section class="d-none d-lg-block topbar">
            <div class="container clearfix">
                <div class="contact-info float-left">
                    <i class="icofont-envelope"></i><a href="mailto:contact@example.com">viettet@gmail.com.vn</a>
                    <i class="icofont-phone"></i> 1800 8098/198
                </div>
                <div class="social-links float-right">
                    <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
                    <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
                    <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
                    <a href="#" class="skype"><i class="icofont-skype"></i></a>
                    <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
                </div>
            </div>
        </section>*@

    <!-- ======= Header ======= -->
    <header id="header">
        <div class="container">

            <div class="logo float-left">
                <a href="/">
                    <img src="~/assets/img/logo_vt.png" />
                </a>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav class="nav-menu float-right d-none d-lg-block">
                <ul>
                    <li><a class="@(ViewData["headerActive"] == "active" ? "" : "active_link")" href="@Request.Url.Scheme://@Request.Url.Host/#hero">Trang chủ</a></li>
                    <li><a href="@Request.Url.Scheme://@Request.Url.Host/#services">Truy cập</a></li>
                    <li><a class="@(ViewData["headerActive"] == "active" ? "active_link" : "")" href="@Request.Url.Scheme://@Request.Url.Host/#utilities">Tiện ích</a></li>
                    <li><a href="@Request.Url.Scheme://@Request.Url.Host/#post">Bài viết</a></li>
                    <li><a href="@Request.Url.Scheme://@Request.Url.Host/#recruitment">Tuyển dụng</a></li>
                    <li>
                        <a id="userDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false" href="/Admin" class="adminCss"><i class="icofont-user-alt-7"> @ViewData["fullNameUser"]</i></a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                            <a style="display: @(ViewData["checkRoleLogin"] == "noLogin" ? "block" : "none")" href=@Url.Action("Index", "LoginForGuest")><i style="margin-right: 10px" class="icofont-login"></i> Login</a>
                            <a style="display: @(ViewData["checkRoleLogin"] == "Admin" ? "block" : "none")" href="/Admin/HomeAdmin"><i style="margin-right: 10px" class="icofont-ui-next"></i> Đi tới trang quản lý</a>
                            <a style="display: @(ViewData["checkRoleLogin"] == "Resolver" ? "block" : "none")" href="/Admin/HandleTruth"><i style="margin-right: 10px" class="icofont-ui-next"></i> Quản lý "Nói Thật đê"</a>
                            <a style="display: @(ViewData["checkRoleLogin"] != "noLogin" ? "block" : "none")" href=@Url.Action("TruthRegestered", "RealTalk")><i style="margin-right: 10px" class="icofont-google-talk"></i>Nói thật đi của bạn</a>
                            <a style="display: @(ViewData["checkRoleLogin"] != "noLogin" ? "block" : "none")" href=@Url.Action("InitativeRegestered", "Initiative")><i style="margin-right: 10px" class="icofont-brand-slideshare"></i>Sáng kiến đã đóng góp</a>
                            <a style="display: @(ViewData["checkRoleLogin"] != "noLogin" ? "block" : "none")" href=@Url.Action("IdeaRegestered", "Idea")><i style="margin-right: 10px" class="icofont-unique-idea"></i>Ý tưởng đã đóng góp</a>
                            <a style="display: @(ViewData["checkRoleLogin"] != "noLogin" ? "block" : "none")" href=@Url.Action("LogOut","Admin/Admin")><i style="margin-right: 10px" class="icofont-logout"></i>Đăng xuất</a>
                        </div>
                    </li>
                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header>

    <!-- Modal check -->
    <div class="modal fade" id="popupCheckRegex" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Thông báo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="contenPopUp" class="modal-body">
                    Vui lòng điền thông tin email Viettel
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-primary">Đồng ý</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Thông báo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Cảm ơn bạn đã gửi thank card
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-primary">Tiếp tục gửi thiệp</button>
                    <a href="@Url.Action("Index","Home")"><button type="button" class="btn btn-danger">Trang chủ</button></a>
                </div>
            </div>
        </div>
    </div>

    @RenderBody()
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div style="display: flex; flex-direction: column; justify-content: center; align-items: center;" class="col-lg-12 col-md-12 footer-info">
                        <h3>Trang tin nội bộ Viettel Software Services</h3>
                        <strong>Phát triển bởi Phòng Kỹ thuật Công nghệ - VSS</strong>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
    <!-- Vendor JS Files -->
    <script src="~/Areas/plugins/ckeditor/ckeditor.js"></script>
    <script src="~/Areas/plugins/ckfinder/ckfinder.js"></script>
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/jquery-sticky/jquery.sticky.js"></script>
    <script src="~/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/assets/vendor/counterup/counterup.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/js/main2.js"></script>
    <script src="~/assets/Tokenfield/dist/bootstrap-tokenfield.js"></script>
    <script src="~/assets/Tokenfield/dist/bootstrap-tokenfield.min.js"></script>
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @RenderSection("scripts", false)
</body>

</html>

vss_portal_web/Views/Shared/_LayoutAllPosts.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Trang tin nội bộ VSS</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/vt.png" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Mamba - v2.0.1
    * Template URL: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Top Bar ======= -->
    @*<section class="d-none d-lg-block topbar">
        <div class="container clearfix">
            <div class="contact-info float-left">
                <i class="icofont-envelope"></i><a href="mailto:contact@example.com">viettet@gmail.com.vn</a>
                <i class="icofont-phone"></i> 1800 8098/198
            </div>
            <div class="social-links float-right">
                <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
                <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
                <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
                <a href="#" class="skype"><i class="icofont-skype"></i></a>
                <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
            </div>
        </div>
    </section>*@

    <!-- ======= Header ======= -->
    <header id="header">
        <div class="container">

            <div class="logo float-left">
                <a href="/">
                    <img src="~/assets/img/logo_vt.png" />
                </a>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav class="nav-menu float-right d-none d-lg-block">

                <ul>
                    <li style=" margin-top: 3px; margin-right: 18px;">
                        @using (Html.BeginForm("Index", "AllPosts", FormMethod.Get))
                        {
                            <div class="row">
                                <input name="searchString" style=" border-radius: 10px; padding: 6px; outline: none; border: 1px #ccc solid; margin-right: 10px; width: 267px;" type="text" placeholder="Tìm kiếm bài viết" />
                                <button style=" outline: none; border-radius: 10px; padding: 4px; border: 1px #ccc solid; background-color: #dc0c2c; color: #fff;" type="submit">Tìm kiếm</button>
                            </div>
                        }
                    </li>
                    <li><a href="/Admin" class="adminCss"><i class="icofont-user-alt-7"></i> @ViewData["UserName"]</a></li>
                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header>
    <!-- End Header -->
    @RenderBody()
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div style="display: flex; flex-direction: column; justify-content: center; align-items: center;" class="col-lg-12 col-md-12 footer-info">
                        <h3>Viettel Software Services</h3>
                        <p>
                            <strong>Office:</strong> 4-5 floor, Thanh Cong Building,
                            80 Dich Vong Hau street, Hanoi<br>
                            <strong>Phone:</strong> 1800 8098/198<br>
                            <strong>Email:</strong> mail.viettel.com.vn<br>

                        </p>
                        <br />
                        <strong>Phát triển bởi Phòng Kỹ thuật Công nghệ - VSS</strong>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/jquery-sticky/jquery.sticky.js"></script>
    <script src="~/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/assets/vendor/counterup/counterup.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @RenderSection("scripts", false)
</body>

</html>