vss_portal_web/Areas/Admin/Controllers/ManageInitativeRegisterController.cs
using DBConect;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vss_portal_web.Areas.Admin.Code;
using vss_portal_web.Controllers;
using vss_portal_web.Models;

namespace vss_portal_web.Areas.Admin.Controllers
{
    public class ManageInitativeRegisterController : BaseAdminController
    {
        private string titleEmail = "Thông báo về việc xét duyệt sáng kiến";
        // GET: Admin/ManageInitativeRegister
        public ActionResult Index(string searchString, int idStatus = 0, int page = 1, int pageSize = 10)
        {
            TempData["myDataRedirect"] = CustomerRedirectLogin.CustomRedirects("Index", "Admin/ManageInitativeRegister");

            var action = new ActionPost();
            var listInitativeRegester = action.GetListInitativeRegester(searchString, idStatus, page, pageSize);
            var status = action.getStatusIdea();
            ViewData["tabBarSelection"] = "manageInitative";
            ViewData["StatusIdeaInitative"] = status;
            ViewData["IdStatusFinter"] = idStatus;
            ViewData["searchString"] = searchString;

            return View(listInitativeRegester);
        }

        [HttpPost]
        public JsonResult ApproveInitativeV2(int id)
        {
            var dataItem = new ActionPost().DetailInitativeRegester(id);

            bool res = false;

            //gửi mail thông báo sáng kiến được phê duyệt
            EmailService service = new EmailService();
            string body = "Sáng kiến: "
                           + dataItem.NameInitative
                           + "của bạn đã được phê duyệt. </br>"
                           + "Tên sáng kiến: " + dataItem.NameInitative
                           + "Thời gian gửi sáng kiến :" + dataItem.TimeSendInitative
                           + "Thời gian phê duyệt:  " + DateTime.Now + " <br/>"
                           +" Người phê duyệt: <br/>" + SessionHelper.GetSessionRoleAdmin().fullName + " <br/>";
            bool resSendMail = service.SendMailAction(dataItem.EmailUserSend, titleEmail, body);

            bool resSendEmailIndividual = true;

            // gửi mail đến từng cá nhân tham gia đóng góp ý kiến
            if (dataItem.MailOfEach != null)
            {
                Array mail = dataItem.MailOfEach.Trim().Split(',');
                foreach (string mailPersion in mail)
                {
                    resSendEmailIndividual = service.SendMailAction(mailPersion, titleEmail, body);
                }
            }

            if (resSendMail)
            {
                bool resApprove = new ActionPost().ApproveInitative(id);
                if (resApprove)
                {
                    res = true;
                }
            }

            return new JsonResult { Data = res, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult RejectInitativeV2(int id)
        {
            var dataItem = new ActionPost().DetailInitativeRegester(id);

            bool res = false;

            //gửi mail thông báo sáng kiến được phê duyệt
            EmailService service = new EmailService();
            string body = "Sáng kiến: "
                          + dataItem.NameInitative
                          + "của bạn đã bị từ chối. </br>"
                          + "Tên sáng kiến :" + dataItem.NameInitative
                          + "Thời gian gửi sáng kiến: " + dataItem.TimeSendInitative
                          + " Thời gian từ chối:  " + DateTime.Now + " <br/>"
                          + " Người phê duyệt: <br/>" + SessionHelper.GetSessionRoleAdmin().fullName + " <br/>";
            bool resSendMail = service.SendMailAction(dataItem.EmailUserSend, titleEmail, body);

            if (resSendMail)
            {
                bool resReject = new ActionPost().RejectInitative(id);
                if (resReject)
                {
                    res = true;
                }
            }

            return new JsonResult { Data = res, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult DetailInitative (int id)
        {
            var detailInitativeRegester = new ActionPost().DetailInitativeRegester(id);
            return View(detailInitativeRegester);
        }

        public FileResult Download(string imgName)
        {

            if (imgName != "")
            {
                var filePath = "~/UploadFiles/FileInitative/" + imgName;
                return File(filePath, "application/force- download", Path.GetFileName(filePath));
            }
            return null;
        }

        public void ExportExcelInitative()
        {
            var action = new ActionPost();
            var listInitativeRegester = action.GetAllListInitativeRegester();

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
            Sheet.Cells["A1"].Value = "Tên sáng kiến";
            Sheet.Cells["B1"].Value = "Tác giả";
            Sheet.Cells["C1"].Value = "Email Viettel";
            Sheet.Cells["D1"].Value = "Đơn vị áp dụng";
            Sheet.Cells["E1"].Value = "Lĩnh vực";
            Sheet.Cells["F1"].Value = "Tình trạng hiện tại";
            Sheet.Cells["G1"].Value = "Điểm mới sáng kiến";
            Sheet.Cells["H1"].Value = "Hiệu quả khi áp dụng";
            Sheet.Cells["I1"].Value = "Nội dung sáng kiến";
            Sheet.Cells["J1"].Value = "Nội dung bổ sung";
            Sheet.Cells["K1"].Value = "Ngày nộp đơn";

            int row = 2;
            foreach (var item in listInitativeRegester)
            {
                Sheet.Cells[string.Format("A{0}", row)].Value = item.NameInitative;
                Sheet.Cells[string.Format("B{0}", row)].Value = item.UserSend;
                Sheet.Cells[string.Format("C{0}", row)].Value = item.EmailUserSend;
                Sheet.Cells[string.Format("D{0}", row)].Value = item.NameUnitApply;
                Sheet.Cells[string.Format("E{0}", row)].Value = item.NameField;
                Sheet.Cells[string.Format("F{0}", row)].Value = item.Applicability;
                Sheet.Cells[string.Format("G{0}", row)].Value = item.NewPoint;
                Sheet.Cells[string.Format("H{0}", row)].Value = item.EffectiveApply;
                Sheet.Cells[string.Format("I{0}", row)].Value = item.ContentInitative;
                Sheet.Cells[string.Format("J{0}", row)].Value = item.DetailMore;
                Sheet.Cells[string.Format("K{0}", row)].Value = item.TimeSendInitative?.ToString("MM/dd/yyyy hh:mm:ss tt");
                row++;
            }


            Sheet.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "InitativeRegester.xlsx");
            Response.BinaryWrite(Ep.GetAsByteArray());
            Response.End();

        }
    }
}

vss_portal_web/Areas/Admin/Views/ManageInitativeRegister/DetailInitative.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin1.cshtml";
}

@model DBConect.model.GetListInitativeRegester

<style>
    .imgRedirect {
        margin-right: 10px
    }

    .soluction::before {
        content: "";
        display: block;
        width: 424px;
        height: 2px;
        background-color: black;
        bottom: -48px;
        left: 269px;
        position: relative;
    }
</style>
<div class="row table_post">
    <div style="height: 30px; width: 100%; display:flex; align-items:center; padding: 0 24px">
        <a href="@Url.Action("Index", "HomeAdmin")" class="imgRedirect">
            <img src="~/Areas/Admin/assets_admin/assets/img/ic_home.png" />
        </a>
        <div class="imgRedirect">
            <img src="~/Areas/Admin/assets_admin/assets/img/ic_arrow_right.png" />
        </div>
        <a href="@Url.Action("Index", "ManageInitativeRegister")" style="color: black; font-size: 20px ; margin-right: 10px">Quản lý sáng kiến</a>
        <div class="imgRedirect">
            <img src="~/Areas/Admin/assets_admin/assets/img/ic_arrow_right.png" />
        </div>
        <div style="color: black; font-size: 20px">Chi tiết ý kiến của - @Model.UserSendFullName</div>
    </div>
    <div style="margin-top: 40px; padding: 0 24px;" class="col-lg-12 mb-4">
        <div class="card" style="min-height: 65vh; display:flex; align-items:center">
            <div style="width: 950px; margin-top: 30px">
                <p style="text-align:center"><span style="font-size:28px"><strong>CỘNG HO&Agrave; X&Atilde; HỘI CHỦ NGHĨA VIỆT NAM</strong></span></p>

                <div class="soluction">
                    <p style="text-align:center"><span style="font-size:20px"><strong>Độc lập - Tự do - Hạnh Ph&uacute;c</strong></span></p>
                </div>

                <p style="text-align:center">&nbsp;</p>

                <p style="text-align:center"><span style="font-size:24px"><strong>ĐƠN ĐĂNG KÝ SÁNG KIẾN</strong></span></p>

                <p style="text-align:center"><span style="font-size:20px">K&iacute;nh gửi: Ban thường trực v&agrave; hội đồng S&aacute;ng kiến &Yacute; tưởng</span></p>

                <p><span style="font-size:16px"><strong>1. &Yacute; tưởng</strong></span></p>

                <p><span style="font-size:14px"><strong>Tên sáng kiến:&nbsp;</strong> @Model.NameInitative</span></p>

                <p><span style="font-size:16px"><strong>2. T&aacute;c giả</strong></span></p>

                <div style="display: flex; align-items:center;">
                    <span style="font-size:14px; flex:1"><strong>Họ v&agrave; t&ecirc;n:&nbsp;</strong> @Model.UserSendFullName</span>
                    <span style="font-size:14px; flex:1"><strong>Email người gửi:</strong> @Model.EmailUserSend</span>
                </div>
                <p></p>

                <p><span style="font-size:14px"><strong>&Yacute; tưởng n&agrave;y của: </strong>@(Model.PersonalInitative ? "Cá nhân" : (Model.InitativeOfDepartment != null ? Model.NameDepartmentSendInitative : "Tập thể nhiều cá nhân"))</span></p>

                <p><span style="font-size:16px"><strong>3. M&ocirc; tả giải ph&aacute;p</strong></span></p>

                <div style="display: flex; align-items:center">
                    <div style="flex:1"><span style="font-size:14px"><strong>3.1 Đơn vị áp dụng:</strong> @Model.NameUnitApply</span></div>

                    <div style="flex: 1"><span style="font-size:14px"><strong>3.2 Lĩnh vực:</strong> @Model.NameField</span></div>
                </div>
                <p></p>

                <p><span style="font-size:16px"><strong>4. Tình trạng hiện tại</strong></span></p>

                <p>- @Model.Applicability</p>

                <p><span style="font-size:16px"><strong>5. Điểm mới của sáng kiến</strong></span></p>

                <p>- @Model.NewPoint</p>

                <p><span style="font-size:16px"><strong>6. Hiệu quả khi áp dụng sáng kiến</strong></span></p>

                <p>- @Model.EffectiveApply</p>

                <p><span style="font-size:16px"><strong>7. Nội dung chi tiết sáng kiến</strong></span></p>

                <p>- @Model.ContentInitative</p>

                <p><span style="font-size:16px"><strong>8.&nbsp; Nội dung bổ sung</strong></span></p>

                <p>- @Model.DetailMore</p>

                <p><span style="font-size:16px"><strong>9. T&agrave;i liệu k&egrave;m theo</strong></span></p>

                <p>
                    @if (Model.NameDocument != null)
                    {
                        @Html.ActionLink("Tải xuông file đính kèm (Click để tải xuống)", "Download", new { imgName = Model.NameDocument.ToString() })
                    }
                    else
                    {
                        <span>Không có tài liệu đi kèm</span>
                    }
                </p>

                <p><span style="font-size:16px"><strong>10 Th&ocirc;ng tin kh&aacute;c</strong></span></p>

                <div style="display: flex; align-items:center;">
                    <span style="font-size:14px; flex:1"><strong>Thời gian đăng k&yacute;:&nbsp;</strong> @(String.Format("{0:dd/MM/yyyy}", Model.TimeSendInitative))</span>
                    <span style="font-size:14px; flex:1"><strong>Trạng th&aacute;i:&nbsp;</strong> @Model.NameStauts</span>
                </div>
                <p></p>

            </div>
        </div>
    </div>
</div>

vss_portal_web/Areas/Admin/Views/ManageInitativeRegister/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin1.cshtml";
}

@model PagedList.IPagedList<DBConect.model.GetListInitativeRegester>
@using PagedList.Mvc
@using DBConect.Farmework
@{
    IEnumerable<StatusIdeaInitative> ListStatus = ViewData["StatusIdeaInitative"] as IEnumerable<StatusIdeaInitative>;
}
<style>
    disabled {
        pointer-events: none;
        cursor: default;
    }

    .pagination-container .pagination li.active {
        background-color: #ccc
    }

    .imgRedirect {
        margin-right: 10px
    }

    select {
        -webkit-appearance: none;
        -moz-appearance: none;
        -ms-appearance: none;
        appearance: none;
        outline: 0;
        box-shadow: none;
        border: 0 !important;
        background: #f5f5f5;
        background-image: none;
    }

    select {
        flex: 1;
        padding: 7px 33px 7px 9px;
        color: #5a4949;
        cursor: pointer;
        border-radius: 11px;
    }
    .table td.name {
        text-overflow: ellipsis;
        overflow: hidden;
        max-width: 300px;
        height: 1.2em;
        white-space: nowrap;
    }
    .nocontent {
        margin-top: 50px;
        padding: 20px;
        background-color: #ccc;
        border-top-left-radius: 30px;
        border-top-right-radius: 30px;
        border-bottom-right-radius: 25px;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        background-image: linear-gradient(to right, #f56383, #ff7524);
        max-width: max-content;
        margin: 69px auto 0 auto;
    }
</style>
<div class="row table_post">
    <div style="height: 30px; width: 100%; display:flex; align-items:center; padding: 0 24px">
        <a href="@Url.Action("Index", "HomeAdmin")" class="imgRedirect">
            <img src="~/Areas/Admin/assets_admin/assets/img/ic_home.png" />
        </a>
        <div class="imgRedirect">
            <img src="~/Areas/Admin/assets_admin/assets/img/ic_arrow_right.png" />
        </div>
        <div style="color: black; font-size: 20px">Quản lý sáng kiến</div>
    </div>
    <div style="margin-top: 40px; padding: 0 24px;" class="col-lg-12 mb-4">
        <div class="card" style="min-height: 65vh; position: relative">
            <div style="width: 100%; margin: 20px 0; padding: 10px 0; display: flex; align-items:center">
                <h4 style=" margin: 0 0 0 20px; color: #dc3545; font-weight:bold; margin-bottom: 15px; flex: 1">Quản lý sáng kiến</h4>
                @using (Html.BeginForm("Index", "ManageInitativeRegister", FormMethod.Get, new { style = "flex: 4" }))
                {
                    <div style="display: flex; align-items:center; margin-right: 30px; flex: 4; justify-content: flex-end">

                        <div style="width: 40%;position: relative; margin-right: 30px">
                            <input value="@ViewData["searchString"]" id="search_input" name="searchString" style=" width: 100%; border: none; background-color: #F5F5F5; border-radius: 17px; padding: 7px 0 6px 35px; outline: none;" placeholder="Tìm kiếm..." />
                            <i style="position: absolute; left: 10px; top: 11px; color: #999999;" class="fas fa-search"></i>
                        </div>
                        <div style="margin-right: 30px; background-color: #5d9866; padding: 7px 10px; border-radius: 13px; display: flex; align-items: center">
                            <i style=" color: #fff; margin-right: 10px;" class="fas fa-file-download"></i>
                            <a style="color: #fff" href="@Url.Action("ExportExcelInitative", "ManageInitativeRegister")">Xuất Excel</a>
                        </div>
                        <div style="position:relative">
                            <select name="idStatus" class="StatusClass" style="border: none" id="IdStatus">
                                <option value=0>Tất cả trạng thái</option>
                                @foreach (StatusIdeaInitative item in ListStatus)
                                {
                                    <option value=@item.IdStatus selected=@(ViewData["IdStatusFinter"].ToString() == item.IdStatus.ToString() ? "selected" : null)>@item.NameStauts</option>
                                }
                            </select>
                            <i style="position: absolute; position: absolute; top: 11px; right: 10px;" class="fas fa-chevron-down"></i>
                        </div>
                        <div>

                        </div>
                        <button id="btnFinterStatus" type="submit" style="visibility: hidden; display: none"></button>
                    </div>
                }
            </div>
            @if (Model.Count > 0)
            {
                <div class="table-responsive" style="margin-bottom: 50px">

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Stt</th>
                                <th>Tên sáng kiến</th>
                                <th>Tác giả</th>
                                <th>Phòng ban tác giả</th>
                                <th>Lĩnh vực</th>
                                <th>Đơn vị áp dụng</th>
                                <th>Sáng kiến của</th>
                                <th>Trạng thái</th>
                                <th>Thời gian gửi</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var data in Model.Select((value, i) => new { value, i }))
                            {
                                var item = data.value;
                                <tr id="row_@item.Id" class="col-tr-post">
                                    <td>@(Math.Abs(data.i + 1))</td>
                                    <td class="name">@item.NameInitative</td>
                                    <td>@item.UserSend</td>
                                    <td>@(item.UserSenDepartment != null ? item.UserSenDepartment : "Không có dữ liệu")</td>
                                    <td>@item.NameField</td>
                                    <td>@item.NameUnitApply</td>
                                    <td>@(item.PersonalInitative == true ? "Cá nhân" : "Tập thể")</td>
                                    <td style="color: @(item.Status == 1 ? "#ff9400" : (item.Status == 2 ? "#08d412" : "red") )">@item.NameStauts</td>
                                    <td>@item.TimeSendInitative</td>
                                    <td style="min-width: 270px">
                                        <a href=@Url.Action("DetailInitative", "ManageInitativeRegister", new { id = item.Id}) class="btn btn-sm btn-primary">Chi Tiết</a>
                                        <div onclick="ApproveInitative(@item.Id)" class="@(item.Status != 1 ? "btn btn-sm btn-success disabled" : "btn btn-sm btn-success")">
                                            Phê duyệt
                                        </div>
                                        <div onclick="RejectInitative(@item.Id)" class="@(item.Status != 1 ? "btn btn-sm btn btn-sm btn-danger disabled" : "btn btn-sm btn-danger")">
                                            Từ chối
                                        </div>
                                        @*@Ajax.ActionLink("Phê duyệt", "ApproveInitative", new { @id = item.Id }, new AjaxOptions
                                    {
                                        Confirm = "Bạn có muốn phê duyệt sáng kiến này?",
                                        OnComplete = "location.reload();",
                                        HttpMethod = "Post"
                                    }, new { @class = item.Status != 1 ? "btn btn-sm btn-success disabled" : "btn btn-sm btn-success" })
                                         @Ajax.ActionLink("Từ chối", "RejectInitative", new { @id = item.Id }, new AjaxOptions
                                    {
                                        Confirm = "Bạn có muốn từ chối sáng kiến này?",
                                        OnComplete = "location.reload();",
                                        HttpMethod = "Post"
                                    }, new { @class = item.Status != 1 ? "btn btn-sm btn-danger disabled" : "btn btn-sm btn-danger" })*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @* spinner *@
                    <div class="spinner">
                        <div class="spinner-border text-danger center-div" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Thông báo</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body contenModels">
                                    Xét duyệt sáng kiến thành công!
                                </div>
                                <div class="modal-footer">
                                    <button type="button" data-dismiss="modal" class="btn btn-primary">Đóng</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="nocontent">
                    Không có dữ liệu
                </div>
            }
            <div style="position: absolute; bottom: 0; left: 0; right: 0;">
                @Html.PagedListPager(Model, page => Url.Action("index", new { page, searchString = ViewData["searchString"], idStatus = ViewData["IdStatusFinter"] }))
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">

        // người dùng xác nhận form model và reload lại trang
        $("#exampleModalCenter").on('hidden.bs.modal', function () {
            location.reload()
        });

        var truthStatus = document.querySelectorAll(".StatusClass");
        truthStatus.forEach(itemTruth => {
            itemTruth.addEventListener('change', function () {
                $("#btnFinterStatus").click();
            })
        })

        $(function () {
            $('input[id=search_input]').keydown(function (e) {
                if (e.keyCode == 13) {
                    $("#btnFinterStatus").click();
                }
            });
        });

        function ApproveInitative(id) {
            if (confirm("Bạn có muốn phê duyệt sáng kiến này?")) {
                $('.spinner').css('display', 'block');
                $.ajax({
                    url: "/ManageInitativeRegister/ApproveInitativeV2",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: `{"id": "${id}"}`,
                    success: function (data) {
                        $('.spinner').css('display', 'none');
                        if (data) {
                            $('#exampleModalCenter').modal('show');
                        } else {
                            $('.contenModels').text("Có lỗi xảy ra, xét duyệt không thành công. Vui lòng thử lại sau ít phút!")
                            $('#exampleModalCenter').modal('show');
                        }
                    }
                })
            } else {
                return false;
            }
        }

        function RejectInitative(id) {
            if (confirm("Bạn có muốn từ chối sáng kiến này?")) {
                $('.spinner').css('display', 'block');
                $.ajax({
                    url: "/ManageInitativeRegister/RejectInitativeV2",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: `{"id": "${id}"}`,
                    success: function (data) {
                        $('.spinner').css('display', 'none');
                        if (data) {
                            $('#exampleModalCenter').modal('show');
                        } else {
                            $('.contenModels').text("Có lỗi xảy ra. Vui lòng thử lại sau ít phút!")
                            $('#exampleModalCenter').modal('show');
                        }
                    }
                })
            } else {
                return false;
            }
        }
    </script>
}